version: '3.8'

services:
  receipt_processor:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app:create_app()
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
